import FooterSpinner from "@/components/Spinner/FooterSpinner";
import { AuthProvider } from "@/components/context/AuthContext";
import { LoadingProvider } from "@/components/context/LoadingContext";
import { CartProvider } from "@/components/context/cart-context";
import Header from "@/components/header/Header";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProvider";
import StoreProvider from "@/components/providers/providers";
import { ThemeProvider } from "@/components/ui/theme-providet";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* <ReactQueryProvider>
            <StoreProvider>
              <AuthProvider>
                <LoadingProvider>
                  <CartProvider>
                    <Header /> */}
                    {children}
                    {/* <footer />
                  </CartProvider>
                  <FooterSpinner />
                </LoadingProvider>
                <Toaster position="bottom-right" />
              </AuthProvider>
            </StoreProvider>
          </ReactQueryProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
